
# siber_arac_v2.py - 200+ Savunma & Etik Hack Araci

lines = [
    '# siber_arac_v2.py',
    '# Bu dosya, savunma ve egitim amacli 200+ adet siber guvenlik aracinin',
    '# yalnizca isimlerini ve kisa, etik/defansif aciklamalarini icerir.',
    '# Hicbir arac icin kotuye kullanim talimati, exploit veya adim adim yonerge icermez.',
    '',
    'TOOLS = [',
]

# Mevcut 100 arac (kullanicinin verdigi)
existing_tools = [
    ('Nmap', 'Ag kesfi ve port taramasi; savunma icin ag envanteri ve beklenmeyen servis tespiti.'),
    ('Masscan', 'Yuksek hizli ag tarayici; buyuk aglarda envanter amacli guvenli tarama (korunmus ortamlarda).'),
    ('Wireshark', 'Paket yakalama ve analiz; ag trafigi inceleme ve anormallik tespiti icin kullanilir.'),
    ('Tcpdump', 'Komut satiri paket yakalama araci; olay mudahalesinde hizli trafik incelemesi.'),
    ('Suricata', 'Ag IDS/IPS: zafiyetleri ve kotu amacli trafigi tespit etmek icin imza ve anomaly destegi.'),
    ('Snort', 'Geleneksel IDS/IPS cozumu; ag tabanli tehdit tespiti ve uyarilar icin kullanilir.'),
    ('Zeek (Bro)', 'Ag guvenlik izleme; zengin protokol analizi ve olay cikarimi saglar.'),
    ('OpenVAS (Greenbone)', 'Acik kaynak zafiyet tarayicisi; savunma odakli zafiyet yonetimi icin raporlar uretir.'),
    ('Nessus', 'Ticari zafiyet degerlendirme araci; kurumlarda duzenli tarama ve risk onceliklendirmesi icin kullanilir.'),
    ('Nikto', 'Web sunucusu zafiyet tarayicisi; savunma amacli kesif icin guvenlik acigi gostergeleri uretir.'),
    ('OWASP ZAP', 'Web uygulama guvenlik testi araci; savunma ekipleri icin otomatik guvenlik taramalari ve tarama sonuclari.'),
    ('Burp Suite (Community)', 'Web uygulama analiz araci; savunma ekipleri icin bulgularin dogrulanmasi ve raporlanmasi amacli kullanilir.'),
    ('Lynis', 'Linux/Unix guvenlik denetim araci; konfigurasyon sertlestirme ve oneriler saglar.'),
    ('OSSEC', 'Host tabanli IDS ve log analiz; dosya butunlugu, log korelasyonu ve uyarilar.'),
    ('Wazuh', 'OSSEC tabanli genisletilmis HIDS ve merkezi yonetim; uygunluk ve guvenlik izlemesi icin.'),
    ('Fail2ban', 'Brute-force tespiti ve gecici engelleme; SSH/servis saldirilarini azaltmaya yardimci olur.'),
    ('ModSecurity', 'Web uygulama guvenlik duvari (WAF); uygulama katmani saldirilarini engelleme ve kaydetme.'),
    ('ClamAV', 'Acik kaynak antivurus motoru; kotu amacli yazilim taramasi ve tespit icin kullanilir.'),
    ('Rkhunter', 'Rootkit tespit araci; bilinen rootkit belirtimlerini kontrol eder.'),
    ('Chkrootkit', 'Sistem uzerinde rootkit belirtilerini arayan basit bir tarayici.'),
    ('AIDE', 'Dosya butunlugu dogrulama araci; degisikliklerin tespiti ve gunluklenmesi icin.'),
    ('Tripwire (Acik kaynak)', 'Dosya butunlugu ve konfigurasyon degisikliklerini izleme araci.'),
    ('auditd', 'Linux denetim altyapisi; sistem cagrilari ve guvenlik olaylarinin kaydi icin.'),
    ('SELinux (tools)', 'Zorunlu erisim kontrolu (MAC) saglayarak surec ve kaynak sinirlandirmasi.'),
    ('AppArmor', 'Alternatif MAC sistemi; uygulamalarin yetkilerini kisitlamak icin profil tabanli kontrol.'),
    ('Sysdig', 'Sistem cagrilari ve konteyner etkinliklerini izleme; olay incelemesi ve forensics icin.'),
    ('Falco', 'Runtime guvenlik izleme; container ve host olaylari icin kural tabanli uyarilar.'),
    ('Prometheus', 'Zaman serisi izleme; guvenlik metrikleri toplayip alarm kurmak icin kullanilir.'),
    ('Grafana', 'Grafik ve dashboard araci; guvenlik ve izleme verilerini gorsellestirmek icin.'),
    ('ELK Stack (Elasticsearch, Logstash, Kibana)', 'Merkezi log toplama, arama ve gorsellestirme; olay korelasyonu ve analiz icin.'),
    ('Graylog', 'Log yonetimi cozumu; merkezi log toplama ve uyari olusturma icin kullanilir.'),
    ('Splunk (Light mention)', 'Gelismis SIEM ve log analizi platformu; kurumsal guvenlik izleme ve sorusturma icin.'),
    ('TheHive', 'Olay mudahalesi platformu; vaka yonetimi ve ekip koordinasyonu icin.'),
    ('Cortex', 'TheHive ile entegre analiz ve otomasyon araclari; IoC ve ornek analizleri icin.'),
    ('MISP', 'Tehdit istihbarati paylasim platformu; IoC paylasimi ve tehdit bilgisinin merkezi yonetimi.'),
    ('OpenCTI', 'Tehdit istihbarati yonetimi; zengin modelleme ve entegrasyon icin.'),
    ('Trivy', 'Konteyner ve imaj guvenlik tarayicisi; bilinen zafiyetlerin tespiti icin.'),
    ('Clair', 'Konteyner goruntusu zafiyet analizi; imajlarda CVE tespiti icin kullanilir.'),
    ('Anchore Engine', 'Konteyner imaj politikasi ve zafiyet taramasi; CI/CD entegrasyonuna uygun.'),
    ('Grype', 'Konteyner/artefakt zafiyet tarayicisi; hizli CVE raporlamasi icin.'),
    ('kube-bench', 'Kubernetes kumeleri icin CIS benchmark denetimleri; sertlestirme kontrolleri saglar.'),
    ('kube-hunter', 'Kubernetes guvenlik degerlendirmesi araci; savunma ekipleri tarafindan kesif sonrasi risk degerlendirmesi icin.'),
    ('kubeaudit', 'Kubernetes kaynaklarini denetleyerek guvenlik aciklari ve kotu konfigurasyonlari raporlar.'),
    ('HashiCorp Vault', 'Guvenli gizli yonetimi; anahtar, token ve sirlarin guvenli saklanmasi icin.'),
    ('GnuPG', 'Sifreleme ve imzalama araci; veri butunlugu ve gizlilik kontrolleri icin.'),
    ('Keycloak', 'Acik kaynak kimlik ve erisim yonetimi; merkezi kimlik dogrulama/SSO saglar.'),
    ('Certbot (Let\'s Encrypt)', 'Otomatik TLS sertifika yonetimi; HTTPS kullanimini kolaylastirir.'),
    ('OpenSSL', 'Kriptografi ve TLS araclari; sertifika dogrulama ve kripto saglik kontrolleri icin.'),
    ('SSLyze', 'TLS yapilandirma analizi; sunucu TLS yapilandirmalarindaki zayifliklari tespit eder.'),
    ('cURL', 'Ag istekleri icin arac; servis kontrolu ve guvenlik dogrulamalari sirasinda kullanilir.'),
    ('Netdata', 'Gercek zamanli performans ve saglik izleme; guvenlik olaylarinin performans gostergeleri icin.'),
    ('Nagios', 'Altyapi izleme; servis ve host durumlarini takip ederek guvenlik olaylarina erken uyari saglar.'),
    ('Zabbix', 'Ag ve uygulama izleme; uyari ve trend analizi icin kullanilabilir.'),
    ('osquery', 'SQL benzeri sorgularla uc nokta gorunurlugu saglar; envanter ve anomali kesfi icin.'),
    ('Velociraptor', 'Uc nokta telemetri ve adli analiz platformu; olay mudahalesinde guclu sorgulama yetenekleri.'),
    ('GRR Rapid Response', 'Uc nokta adli analiz ve uzaktan mudahale; buyuk olcekli olay mudahalesi icin.'),
    ('Autopsy', 'Dijital adli analiz arayuzu; dosya sistemleri ve goruntuler uzerinde inceleme yapar.'),
    ('Sleuth Kit', 'Adli analiz icin komuta satiri kutuphaneleri ve araclar; veri kurtarma ve delil toplama icin.'),
    ('Volatility', 'Bellek adli analizi; bellek goruntulerinden IoC ve kotu amacli surec tespiti.'),
    ('Bulk Extractor', 'Dijital goruntulerden toplu veri cikarimi; IoC ve yapilandirma verisi elde etmek icin.'),
    ('Scalpel', 'Dosya carve araci; silinmis verilerin kurtarilmasi ve adli analiz icin.'),
    ('Foremost', 'Dosya kurtarma ve carve etme; adli verilerin cikartilmasi icin kullanilir.'),
    ('Plaso (log2timeline)', 'Zaman cizelgesi olusturma araci; olay korelasyonu ve olay zamansal analizi icin.'),
    ('Filebeat', 'Kucuk hafif log gonderici; merkezi log sistemlerine veri iletmek icin.'),
    ('Packetbeat', 'Ag trafigi metriklerini toplayan Beat; uygulama protokollerini izlemede kullanilir.'),
    ('Auditbeat', 'Host davranisi ve uygunluk icin Beat; surec, dosya ve kullanici aktivitelerini toplar.'),
    ('Ansible', 'Konfigurasyon yonetimi ve otomasyon; guvenlik yamalarinin dagitimi ve konfigurasyon sertlestirme icin.'),
    ('Puppet', 'Konfigurasyon yonetimi araci; tutarli guvenlik konfigurasyonlari icin.'),
    ('Chef', 'Altyapi otomasyonu; guvenlik politikalarinin otomatik uygulanmasi icin.'),
    ('SaltStack', 'Uzaktan yurutme ve konfigurasyon yonetimi; hizli mudahale ve duzeltme islemleri icin.'),
    ('OpenSCAP', 'Sertlestirme ve uygunluk denetimleri; SCAP profilleri uzerinden denetim saglar.'),
    ('Bandit', 'Python kodu icin statik guvenlik tarayicisi; guvenlik aciklari ve zayif kod oruntulerini bulmaya yardimci olur.'),
    ('Brakeman', 'Ruby on Rails uygulamalari icin statik guvenlik analiz araci.'),
    ('Semgrep', 'Hafif, hizli statik analiz ve guvenlik kurallari yazma araci; CI entegrasyonuna uygun.'),
    ('TruffleHog', 'Git gecmisinde gizli anahtarlar ve hassas bilgi arama; kod deposu gizli sizintilarini onlemek icin.'),
    ('Gitleaks', 'Depolarda gizli anahtar tespiti; CI/CD icinde yasa disi sizintilari yakalamak icin.'),
    ('SonarQube', 'Kod kalitesi ve guvenlik aciklari icin surekli analiz platformu.'),
    ('Dependabot', 'Bagimlilik guncellemelerini otomatik oneren arac; zafiyetli paketlerin guncellenmesine yardimci olur.'),
    ('Snyk', 'Bagimlilik ve container zafiyet taramasi; gelistirme surecine entegre guvenlik.'),
    ('BorgBackup', 'Icerik adresli yedekleme; sifreleme ve sikistirma ile guvenli yedekler olusturur.'),
    ('Restic', 'Hafif, guvenli yedekleme araci; sifreli yedeklerle veri koruma saglar.'),
    ('Duplicity', 'Sifreli yedekleme ve uzak depolama icin kullanilan arac.'),
    ('Bacula', 'Kurum ici yedekleme, geri yukleme ve dogrulama cozumleri sunan paket.'),
    ('rsync', 'Dosya senkronizasyonu ve yedekleme icin guvenilir arac; yedekleme prosedurlerinde temel yapi tasi.'),
    ('iptables / nftables', 'Linux tabanli paket filtreleme ve firewall kurallari; agdan gelen trafigi kontrol etme.'),
    ('UFW (Uncomplicated Firewall)', 'Basit Linux firewall yonetimi; hizli kurallar ve engelleme icin kullanilabilir.'),
    ('pfSense', 'Acik kaynak firewall/router dagitimi; sinir guvenligi ve ag segmentasyonu icin.'),
    ('OpenVPN', 'VPN cozumu; guvenli uzak erisim ve site-to-site baglantilar icin.'),
    ('WireGuard', 'Modern, hizli VPN protokolu; basit ve guvenli baglantilar saglamak icin.'),
    ('StrongSwan', 'IPsec tabanli VPN cozumu; kurumsal baglantilar icin guvenli tunelleme.'),
    ('ntopng', 'Ag trafigi analizoru; akis tabanli analiz ve davranis modelleme icin.'),
    ('OSQuery (again noted)', 'Uc nokta sorgulama icin guclu bir arac; envanter, izlemesi ve anomali tespiti.'),
]

for name, desc in existing_tools:
    lines.append(f'    {{"name": "{name}", "description": "{desc}"}},')

print(f"Mevcut {len(existing_tools)} arac eklendi.")
